# Site settings
title: "Letf Hand Way"
bye_message: "Thx!"
baseurl: "/naige9.github.io/"
url: "https://lefthandway.pl"
disqus: naige9

# Header settings
nick: "naige9"
mail:
    domain: "lefthandway"
    ext: "pl"
source_code:
    server: "github.com"
    nick: "naige9"
#blog:
#    server: "wordpress.com"
#    nick: "gjuniioor"
#fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
